package com.example.jingleski.midtier.operations;


/**
 * Created by jingleski on 25.12.17.
 *
 * checks whether the multiplication of the factors is equal to the given solution
 */

public class Multiplication implements Operation {

    /**
     *
     * @param numbers The factors generated by the application
     * @param solution The solution given in by the user
     * @return Is the multiplication of the factors equal to the given solution?
     * <br /> process([2,2],3) returns false
     * <br /> process[2,2],4) returns true
     */
    public boolean process(int[] numbers, int solution){

        int total = 1;
        for(int factor:numbers){
            total*=factor;
        }
        return total==solution;

    }

}
